# General
server:
    port: 8080
    error:
        include-stacktrace: NEVER

### MariaDB
spring:
  datasource:
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/stockalarm

  jpa:
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    show-sql: false
    hibernate:
      ddl-auto: none

  # Flyway configurations
  flyway:
    baseline-on-migrate: 'true'
    locations: classpath:/db/migration
    table: schema_history
# Required for Postgres
#spring.flyway.schemas=public


### Custom configurations

# Stock

#check stock interval in ms
stock:
  check:
    interval: ${STOCK_CHECK_INTERVAL:30000}

# Email
email:
  is:
    enabled: 'false'
  from:
    address: ferenc.dev.1@gmail.com
  password: 5mJdV\TN